theme: jekyll-theme-minimal
title: [Welcome to my Portfolio]
description: [This will be my Portfolio of some projects/assignments I developed as a collage student here at Western Oregon University.]
logo: ["Images/DanielTapia.JPG"]
show_downloads: ["true"]